export function getMediaItems() {
  return [
    {
      id: '1',
      title: 'Modern Office Collaboration',
      type: 'image',
      url: '/placeholder.svg',
      thumbnailUrl: '/placeholder.svg',
      size: 1250000,
      uploadDate: '2023-05-15T10:30:00Z',
      description: 'Team working together in a modern office environment',
      tags: ['office', 'collaboration', 'team'],
      width: 1920,
      height: 1080
    },
    {
      id: '2',
      title: 'Tech Product Display',
      type: 'image',
      url: '/placeholder.svg',
      thumbnailUrl: '/placeholder.svg',
      size: 980000,
      uploadDate: '2023-06-22T14:45:00Z',
      description: 'Modern technology product on display',
      tags: ['product', 'technology', 'display'],
      width: 1600,
      height: 900
    },
    {
      id: '3',
      title: 'Diverse Business Team',
      type: 'image',
      url: '/placeholder.svg',
      thumbnailUrl: '/placeholder.svg',
      size: 1100000,
      uploadDate: '2023-07-10T09:15:00Z',
      description: 'Diverse group of professionals in a business meeting',
      tags: ['business', 'team', 'diversity'],
      width: 1800,
      height: 1200
    },
    {
      id: '4',
      title: 'Dynamic Product Showcase',
      type: 'image',
      url: '/placeholder.svg',
      thumbnailUrl: '/placeholder.svg',
      size: 1350000,
      uploadDate: '2023-08-05T16:20:00Z',
      description: 'Dynamic presentation of a new product',
      tags: ['product', 'showcase', 'marketing'],
      width: 2000,
      height: 1200
    },
    {
      id: '5',
      title: 'Abstract Geometric Shapes',
      type: 'image',
      url: '/placeholder.svg',
      thumbnailUrl: '/placeholder.svg',
      size: 850000,
      uploadDate: '2023-09-12T11:40:00Z',
      description: 'Abstract geometric pattern for backgrounds',
      tags: ['abstract', 'geometric', 'background'],
      width: 1600,
      height: 1600
    },
    {
      id: '6',
      title: 'Stapler Rebellion',
      type: 'image',
      url: '/placeholder.svg',
      thumbnailUrl: '/placeholder.svg',
      size: 720000,
      uploadDate: '2023-10-01T08:25:00Z',
      description: 'Humorous office supply arrangement',
      tags: ['humor', 'office', 'supplies'],
      width: 1200,
      height: 800
    },
    {
      id: '7',
      title: 'Blog Platform Demo',
      type: 'video',
      url: '/placeholder.svg',
      thumbnailUrl: '/placeholder.svg',
      size: 24500000,
      uploadDate: '2023-11-15T13:50:00Z',
      description: 'Demo video for the blog platform',
      tags: ['demo', 'tutorial', 'blog'],
      width: 1280,
      height: 720
    },
    {
      id: '8',
      title: 'Store Logo',
      type: 'image',
      url: '/placeholder.svg',
      thumbnailUrl: '/placeholder.svg',
      size: 450000,
      uploadDate: '2023-12-20T10:10:00Z',
      description: 'Official Store logo in high resolution',
      tags: ['logo', 'branding', 'official'],
      width: 2000,
      height: 2000
    },
    {
      id: '9',
      title: 'Database Structure',
      type: 'image',
      url: '/placeholder.svg',
      thumbnailUrl: '/placeholder.svg',
      size: 680000,
      uploadDate: '2024-01-05T15:30:00Z',
      description: 'Diagram showing the database structure',
      tags: ['diagram', 'database', 'technical'],
      width: 1800,
      height: 1000
    },
    {
      id: '10',
      title: 'Modern Dashboard Interface',
      type: 'image',
      url: '/placeholder.svg',
      thumbnailUrl: '/placeholder.svg',
      size: 920000,
      uploadDate: '2024-02-10T09:45:00Z',
      description: 'Screenshot of the modern dashboard interface',
      tags: ['dashboard', 'interface', 'ui'],
      width: 1920,
      height: 1080
    },
    {
      id: '11',
      title: 'Dark Mode Portfolio',
      type: 'image',
      url: '/placeholder.svg',
      thumbnailUrl: '/placeholder.svg',
      size: 1050000,
      uploadDate: '2024-03-18T14:20:00Z',
      description: 'Portfolio website in dark mode',
      tags: ['portfolio', 'dark mode', 'website'],
      width: 1600,
      height: 900
    },
    {
      id: '12',
      title: 'E-commerce Products',
      type: 'image',
      url: '/placeholder.svg',
      thumbnailUrl: '/placeholder.svg',
      size: 1150000,
      uploadDate: '2024-04-05T11:15:00Z',
      description: 'Product display for e-commerce website',
      tags: ['e-commerce', 'products', 'retail'],
      width: 1800,
      height: 1200
    }
  ]
}
